// World Bank indicator codes and the country list used across modules.

export const INDICATORS = {
  gdpGrowth: 'NY.GDP.MKTP.KD.ZG',
  gdpPerCapita: 'NY.GDP.PCAP.CD',
  inflation: 'FP.CPI.TOTL.ZG',
  unemployment: 'SL.UEM.TOTL.ZS',
  lifeExpectancy: 'SP.DYN.LE00.IN',
  tradePercentGdp: 'NE.TRD.GNFS.ZS',
  fdiInflows: 'BX.KLT.DINV.WD.GD.ZS',
  gdpPerCapitaPpp: 'NY.GDP.PCAP.PP.CD',
  pppFactor: 'PA.NUS.PPP',
  population: 'SP.POP.TOTL',
  populationGrowth: 'SP.POP.GROW',
  urbanShare: 'SP.URB.TOTL.IN.ZS',
  fertility: 'SP.DYN.TFRT.IN',
  overSixtyFive: 'SP.POP.65UP.TO.ZS',
  dependency: 'SP.POP.DPND',
} as const

// Statistical Performance Indicators: the World Bank's own published measure
// of how well a national statistical system works.
export const SPI = {
  overall: 'IQ.SPI.OVRL',
  dataUse: 'IQ.SPI.PIL1',
  dataServices: 'IQ.SPI.PIL2',
  dataProducts: 'IQ.SPI.PIL3',
  dataSources: 'IQ.SPI.PIL4',
  dataInfrastructure: 'IQ.SPI.PIL5',
} as const

export type IndicatorKey = keyof typeof INDICATORS

export interface Country {
  code: string
  name: string
}

export const COUNTRIES: Country[] = [
  { code: 'KAZ', name: 'Kazakhstan' },
  { code: 'RUS', name: 'Russia' },
  { code: 'USA', name: 'United States' },
  { code: 'CHN', name: 'China' },
  { code: 'DEU', name: 'Germany' },
  { code: 'FRA', name: 'France' },
  { code: 'GBR', name: 'United Kingdom' },
  { code: 'JPN', name: 'Japan' },
  { code: 'TUR', name: 'Turkiye' },
  { code: 'IRN', name: 'Iran' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'IND', name: 'India' },
  { code: 'POL', name: 'Poland' },
  { code: 'UZB', name: 'Uzbekistan' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'KOR', name: 'South Korea' },
  { code: 'ITA', name: 'Italy' },
  { code: 'ESP', name: 'Spain' },
  { code: 'CHE', name: 'Switzerland' },
  { code: 'NOR', name: 'Norway' },
  { code: 'BLR', name: 'Belarus' },
  { code: 'VEN', name: 'Venezuela' },
]

export function countryName(code: string): string {
  return COUNTRIES.find((country) => country.code === code)?.name ?? code
}

// The World Bank API only publishes country names in English, so the names
// people are most likely to look for are translated here. Anything outside
// this map falls back to the English name.
export const COUNTRY_NAMES_RU: Record<string, string> = {
  ABW: 'Аруба',
  AFG: 'Афганистан',
  AGO: 'Ангола',
  ALB: 'Албания',
  AND: 'Андорра',
  ARE: 'ОАЭ',
  ARG: 'Аргентина',
  ARM: 'Армения',
  ASM: 'Американское Самоа',
  ATG: 'Антигуа и Барбуда',
  AUS: 'Австралия',
  AUT: 'Австрия',
  AZE: 'Азербайджан',
  BDI: 'Бурунди',
  BEL: 'Бельгия',
  BEN: 'Бенин',
  BFA: 'Буркина-Фасо',
  BGD: 'Бангладеш',
  BGR: 'Болгария',
  BHR: 'Бахрейн',
  BHS: 'Багамские Острова',
  BIH: 'Босния и Герцеговина',
  BLR: 'Беларусь',
  BLZ: 'Белиз',
  BMU: 'Бермудские Острова',
  BOL: 'Боливия',
  BRA: 'Бразилия',
  BRB: 'Барбадос',
  BRN: 'Бруней',
  BTN: 'Бутан',
  BWA: 'Ботсвана',
  CAF: 'Центральноафриканская Республика',
  CAN: 'Канада',
  CHE: 'Швейцария',
  CHI: 'Нормандские Острова',
  CHL: 'Чили',
  CHN: 'Китай',
  CIV: 'Кот-д’Ивуар',
  CMR: 'Камерун',
  COD: 'ДР Конго',
  COG: 'Республика Конго',
  COL: 'Колумбия',
  COM: 'Коморские Острова',
  CPV: 'Кабо-Верде',
  CRI: 'Коста-Рика',
  CUB: 'Куба',
  CUW: 'Кюрасао',
  CYM: 'Каймановы Острова',
  CYP: 'Кипр',
  CZE: 'Чехия',
  DEU: 'Германия',
  DJI: 'Джибути',
  DMA: 'Доминика',
  DNK: 'Дания',
  DOM: 'Доминиканская Республика',
  DZA: 'Алжир',
  ECU: 'Эквадор',
  EGY: 'Египет',
  ERI: 'Эритрея',
  ESP: 'Испания',
  EST: 'Эстония',
  ETH: 'Эфиопия',
  FIN: 'Финляндия',
  FJI: 'Фиджи',
  FRA: 'Франция',
  FRO: 'Фарерские Острова',
  FSM: 'Микронезия',
  GAB: 'Габон',
  GBR: 'Великобритания',
  GEO: 'Грузия',
  GHA: 'Гана',
  GIB: 'Гибралтар',
  GIN: 'Гвинея',
  GMB: 'Гамбия',
  GNB: 'Гвинея-Бисау',
  GNQ: 'Экваториальная Гвинея',
  GRC: 'Греция',
  GRD: 'Гренада',
  GRL: 'Гренландия',
  GTM: 'Гватемала',
  GUM: 'Гуам',
  GUY: 'Гайана',
  HKG: 'Гонконг',
  HND: 'Гондурас',
  HRV: 'Хорватия',
  HTI: 'Гаити',
  HUN: 'Венгрия',
  IDN: 'Индонезия',
  IMN: 'Остров Мэн',
  IND: 'Индия',
  IRL: 'Ирландия',
  IRN: 'Иран',
  IRQ: 'Ирак',
  ISL: 'Исландия',
  ISR: 'Израиль',
  ITA: 'Италия',
  JAM: 'Ямайка',
  JOR: 'Иордания',
  JPN: 'Япония',
  KAZ: 'Казахстан',
  KEN: 'Кения',
  KGZ: 'Кыргызстан',
  KHM: 'Камбоджа',
  KIR: 'Кирибати',
  KNA: 'Сент-Китс и Невис',
  KOR: 'Южная Корея',
  KWT: 'Кувейт',
  LAO: 'Лаос',
  LBN: 'Ливан',
  LBR: 'Либерия',
  LBY: 'Ливия',
  LCA: 'Сент-Люсия',
  LIE: 'Лихтенштейн',
  LKA: 'Шри-Ланка',
  LSO: 'Лесото',
  LTU: 'Литва',
  LUX: 'Люксембург',
  LVA: 'Латвия',
  MAC: 'Макао',
  MAF: 'Сен-Мартен',
  MAR: 'Марокко',
  MCO: 'Монако',
  MDA: 'Молдова',
  MDG: 'Мадагаскар',
  MDV: 'Мальдивы',
  MEX: 'Мексика',
  MHL: 'Маршалловы Острова',
  MKD: 'Северная Македония',
  MLI: 'Мали',
  MLT: 'Мальта',
  MMR: 'Мьянма',
  MNE: 'Черногория',
  MNG: 'Монголия',
  MNP: 'Северные Марианские Острова',
  MOZ: 'Мозамбик',
  MRT: 'Мавритания',
  MUS: 'Маврикий',
  MWI: 'Малави',
  MYS: 'Малайзия',
  NAM: 'Намибия',
  NCL: 'Новая Каледония',
  NER: 'Нигер',
  NGA: 'Нигерия',
  NIC: 'Никарагуа',
  NLD: 'Нидерланды',
  NOR: 'Норвегия',
  NPL: 'Непал',
  NRU: 'Науру',
  NZL: 'Новая Зеландия',
  OMN: 'Оман',
  PAK: 'Пакистан',
  PAN: 'Панама',
  PER: 'Перу',
  PHL: 'Филиппины',
  PLW: 'Палау',
  PNG: 'Папуа Новая Гвинея',
  POL: 'Польша',
  PRI: 'Пуэрто-Рико',
  PRK: 'КНДР',
  PRT: 'Португалия',
  PRY: 'Парагвай',
  PSE: 'Палестина',
  PYF: 'Французская Полинезия',
  QAT: 'Катар',
  ROU: 'Румыния',
  RUS: 'Россия',
  RWA: 'Руанда',
  SAU: 'Саудовская Аравия',
  SDN: 'Судан',
  SEN: 'Сенегал',
  SGP: 'Сингапур',
  SLB: 'Соломоновы Острова',
  SLE: 'Сьерра-Леоне',
  SLV: 'Сальвадор',
  SMR: 'Сан-Марино',
  SOM: 'Сомали',
  SRB: 'Сербия',
  SSD: 'Южный Судан',
  STP: 'Сан-Томе и Принсипи',
  SUR: 'Суринам',
  SVK: 'Словакия',
  SVN: 'Словения',
  SWE: 'Швеция',
  SWZ: 'Эсватини',
  SXM: 'Синт-Мартен',
  SYC: 'Сейшельские Острова',
  SYR: 'Сирия',
  TCA: 'Теркс и Кайкос',
  TCD: 'Чад',
  TGO: 'Того',
  THA: 'Таиланд',
  TJK: 'Таджикистан',
  TKM: 'Туркменистан',
  TLS: 'Восточный Тимор',
  TON: 'Тонга',
  TTO: 'Тринидад и Тобаго',
  TUN: 'Тунис',
  TUR: 'Турция',
  TUV: 'Тувалу',
  TZA: 'Танзания',
  UGA: 'Уганда',
  UKR: 'Украина',
  URY: 'Уругвай',
  USA: 'США',
  UZB: 'Узбекистан',
  VCT: 'Сент-Винсент и Гренадины',
  VEN: 'Венесуэла',
  VGB: 'Британские Виргинские Острова',
  VIR: 'Виргинские Острова США',
  VNM: 'Вьетнам',
  VUT: 'Вануату',
  WSM: 'Самоа',
  XKX: 'Косово',
  YEM: 'Йемен',
  ZAF: 'ЮАР',
  ZMB: 'Замбия',
  ZWE: 'Зимбабве',
}
