import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import { Info, ChevronDown, AlertTriangle, House, Calculator, BookOpen, GitCompare, Minus, Plus } from 'lucide-react'
import { ElasticSlider, PageLayout } from '../../../shared/components'
import { useI18n } from '../../../shared/i18n'
import { calculateDeal, type DealInputs } from './calculator'
import { scenarios } from './scenarios'
import { strategies } from './strategies'
import { lessons } from './lessons'
import { sampleProperties } from './sampleProperties'
import styles from './PropertyLabPage.module.css'

const defaults: DealInputs = { price: 220000, down: 20, rate: 6.75, term: 30, rent: 1800, vacancy: 6, taxes: 3000, insurance: 1200, maintenance: 5, capex: 5, management: 8, utilities: 0, hoa: 180, closing: 3, renovation: 5000, leasing: 3, rentGrowth: 3, expenseGrowth: 3, appreciation: 3, reserve: 12000 }
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)
const pct = (n: number) => `${(n * 100).toFixed(1)}%`

export default function PropertyLabPage() {
  const { t } = useI18n()
  const [input, setInput] = useState(defaults)
  const [scenario, setScenario] = useState('base')
  const [event, setEvent] = useState('none')
  const [open, setOpen] = useState('calculator')
  const eventAdjustments: Partial<DealInputs> = event === 'vacancy' ? { vacancy: input.vacancy + 8 } : event === 'rent' ? { rent: input.rent * 0.9 } : event === 'insurance' ? { insurance: input.insurance * 1.25 } : event === 'taxes' ? { taxes: input.taxes * 1.2 } : event === 'rates' ? { rate: input.rate + 2 } : event === 'repair' ? { renovation: input.renovation + 12000 } : event === 'refinance' ? { closing: input.closing + 2, rate: Math.max(0, input.rate - 0.5) } : {}
  const result = useMemo(() => calculateDeal(input, { ...scenarios.find((s) => s.id === scenario)?.adjustments, ...eventAdjustments }), [input, scenario, event])
  const comparisonRows = useMemo(() => scenarios.slice(0, 6).map((s) => ({ ...s, result: calculateDeal(input, { ...s.adjustments, ...eventAdjustments }) })), [input, event])
  const comparisons = comparisonRows.map((s) => ({ name: s.label.replace(' case', ''), cash: Math.round(s.result.monthlyCashFlow) }))
  const update = (key: keyof DealInputs, value: string) => setInput((current) => ({ ...current, [key]: Number(value) || 0 }))
  const warnings = [input.vacancy < 3 && 'Vacancy below 3% may understate income risk.', input.maintenance + input.capex < 8 && 'Maintenance and capex reserves are below a conservative 8% combined.', result.monthlyCashFlow < 0 && 'This scenario produces negative monthly cash flow.', result.dscr < 1 && 'DSCR below 1.0x means income does not cover scheduled debt.', input.down < 15 && 'Very high leverage increases sensitivity to shocks.', input.reserve < result.expenses * 3 && 'Emergency reserve is below three months of operating expenses.'].filter(Boolean) as string[]
  const fields: [keyof DealInputs, string, string, number][] = [['price', 'Purchase price', '$', 1000000], ['down', 'Down payment', '%', 80], ['rate', 'Mortgage rate', '%', 15], ['term', 'Loan term', 'years', 40], ['rent', 'Monthly rent', '$', 10000], ['vacancy', 'Vacancy rate', '%', 40], ['taxes', 'Property taxes', '$/yr', 20000], ['insurance', 'Insurance', '$/yr', 10000], ['maintenance', 'Maintenance', '% rent', 20], ['capex', 'Capex reserve', '% rent', 20], ['management', 'Property management', '% rent', 20], ['utilities', 'Utilities', '$/mo', 2000], ['hoa', 'HOA fees', '$/mo', 2000], ['closing', 'Closing costs', '% price', 15], ['renovation', 'Renovation costs', '$', 100000], ['leasing', 'Leasing costs', '% rent', 15], ['rentGrowth', 'Annual rent growth', '%', 10], ['expenseGrowth', 'Annual expense growth', '%', 10], ['appreciation', 'Property appreciation', '%', 10], ['reserve', 'Emergency reserve', '$', 100000]]
  return <PageLayout title={t('nav.property')} subtitle={t('prop.subtitle')}>
    <div className={styles.notice}>{t('prop.notice')}</div>
    <section className={styles.hero}><div><span className={styles.eyebrow}>{t('prop.workspace')}</span><h2>{money(result.monthlyCashFlow)} <small>{t('prop.monthlyCash')}</small></h2><p>Change an assumption or scenario to see how the property responds immediately.</p></div><div className={styles.heroMetric}><span>DSCR</span><strong>{result.dscr.toFixed(2)}x</strong><em>{result.dscr >= 1.25 ? 'Debt has coverage' : 'Test a safer case'}</em></div></section>
    <Section icon={Calculator} title={t('prop.calculator')} id="calculator" open={open === 'calculator'} onClick={() => setOpen(open === 'calculator' ? '' : 'calculator')}>
      <div className={styles.calculator}><div className={styles.inputGrid}>{fields.map(([key, label, unit, max]) => <label className={styles.field} key={key}><span>{label}<small>{unit}</small></span><input type="number" min="0" max={max} step="any" value={input[key]} onChange={(e) => update(key, e.target.value)} /><ElasticSlider value={input[key]} startingValue={0} maxValue={max} isStepped stepSize={key === 'price' || key === 'rent' || key === 'taxes' || key === 'insurance' || key === 'hoa' || key === 'renovation' || key === 'reserve' ? 100 : 0.25} leftIcon={<Minus size={12} />} rightIcon={<Plus size={12} />} onChange={(next) => update(key, String(next))} /></label>)}</div><div className={styles.results}>{[['Mortgage payment', money(result.mortgage), 'Principal and interest payment.'], ['Gross rent', money(result.grossRent), 'Scheduled rent before vacancy.'], ['Operating expenses', money(result.expenses), 'Vacancy-adjusted operating costs before debt.'], ['NOI', money(result.noi / 12) + '/mo', 'Annual rent less operating expenses, before debt.'], ['Annual cash flow', money(result.annualCash), 'Pre-tax cash flow after debt service.'], ['Cap rate', pct(result.capRate), 'Annual NOI divided by purchase price.'], ['Cash on cash', pct(result.cashOnCash), 'Annual pre-tax cash flow divided by initial cash invested.'], ['Break-even occupancy', pct(result.breakEvenOccupancy), 'Occupancy needed to cover operating costs and debt.'], ['Initial cash required', money(result.initialCash), 'Down payment plus upfront costs.'], ['5-year equity', money(result.equity), 'Projected value less the exact remaining loan balance.'], ['5-year total return', money(result.fiveYearReturn), 'Estimated equity gain plus five years of cash flow.']].map(([label, value, tip]) => <div className={styles.result} key={label}><span title={tip}>{label}<Info size={12} /></span><strong>{value}</strong></div>)}</div></div>
      <details className={styles.assumptions}><summary>Assumptions used in these results <ChevronDown size={15} /></summary><p>Price {money(input.price)} · {input.down}% down · {input.rate}% / {input.term} years · rent {money(input.rent)} · vacancy {input.vacancy}% · taxes {money(input.taxes)}/yr · insurance {money(input.insurance)}/yr · operating reserves {input.maintenance + input.capex}% of rent · appreciation {input.appreciation}%.</p></details>
      {warnings.length > 0 && <div className={styles.warnings}>{warnings.map((warning) => <p key={warning}><AlertTriangle size={15} />{warning}</p>)}</div>}
    </Section>
    <Section icon={GitCompare} title={t('prop.scenarios')} id="scenarios" open={open === 'scenarios'} onClick={() => setOpen(open === 'scenarios' ? '' : 'scenarios')}><div className={styles.scenarioTabs}>{scenarios.map((s) => <button className={scenario === s.id ? styles.selected : ''} key={s.id} onClick={() => setScenario(s.id)}>{s.label}<small>{s.note}</small></button>)}</div><label className={styles.eventSelect}>Educational event to model<select value={event} onChange={(e) => setEvent(e.target.value)}><option value="none">No additional event</option><option value="vacancy">Tenant vacancy shock</option><option value="rent">Rent reduction</option><option value="insurance">Insurance increase</option><option value="taxes">Property tax increase</option><option value="rates">Interest rate reset</option><option value="repair">Emergency repair / roof replacement</option><option value="refinance">Refinancing costs</option></select></label><div className={styles.chart}><ResponsiveContainer width="100%" height={240}><BarChart data={comparisons}><CartesianGrid stroke="var(--color-border)" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#8b90a5', fontSize: 11 }} /><YAxis tick={{ fill: '#8b90a5', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#10101c', border: '1px solid #20243a' }} formatter={(v) => [money(Number(v)), 'Monthly cash flow']} /><Bar dataKey="cash" fill="var(--color-accent)" /></BarChart></ResponsiveContainer></div><div className={styles.tableWrap}><table><thead><tr><th>Scenario</th><th>Monthly cash flow</th><th>Annual cash flow</th><th>Cap rate</th><th>Cash on cash</th><th>DSCR</th><th>Reserve coverage</th><th>5-year return</th></tr></thead><tbody>{comparisonRows.map((s) => <tr key={s.id}><td>{s.label}</td><td>{money(s.result.monthlyCashFlow)}</td><td>{money(s.result.annualCash)}</td><td>{pct(s.result.capRate)}</td><td>{pct(s.result.cashOnCash)}</td><td>{s.result.dscr.toFixed(2)}x</td><td>{s.result.reserveCoverage.toFixed(1)} mo</td><td>{money(s.result.fiveYearReturn)}</td></tr>)}</tbody></table></div><p className={styles.eventNote}>Each event represents an operating risk to understand, not a game of chance. Test one at a time and compare the reason for the change.</p></Section>
    <Section icon={GitCompare} title={t('prop.strategies')} id="strategies" open={open === 'strategies'} onClick={() => setOpen(open === 'strategies' ? '' : 'strategies')}><div className={styles.tableWrap}><table><thead><tr><th>Strategy</th><th>Cash required</th><th>Liquidity</th><th>Leverage</th><th>Time</th><th>Complexity</th><th>Income</th><th>Main risks</th><th>Beginner profile</th></tr></thead><tbody>{strategies.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></Section>
    <Section icon={BookOpen} title={t('prop.learning')} id="learning" open={open === 'learning'} onClick={() => setOpen(open === 'learning' ? '' : 'learning')}><div className={styles.lessons}>{lessons.map(([term, definition, example, question, answer]) => <details key={term}><summary>{term}<ChevronDown size={14} /></summary><p>{definition}</p><code>{example}</code><strong>{question}</strong><p>{answer}</p></details>)}</div></Section>
    <Section icon={House} title={t('prop.preview')} id="preview" open={open === 'preview'} onClick={() => setOpen(open === 'preview' ? '' : 'preview')}><p className={styles.muted}>Fictional sample properties for future paper ownership exercises.</p><div className={styles.properties}>{sampleProperties.map((property) => <article key={property.location}><div className={styles.placeholder}><House size={22} /></div><span className={styles.eyebrow}>Educational simulation data</span><h3>{property.location}</h3><p>{property.type}</p><strong>{money(property.price)}</strong><span>{money(property.rent)}/mo rent · {money(property.expenses)}/mo expenses · {property.vacancy} vacancy</span></article>)}</div></Section>
  </PageLayout>
}

function Section({ icon: Icon, title, id, open, onClick, children }: { icon: typeof Calculator; title: string; id: string; open: boolean; onClick: () => void; children: ReactNode }) { return <section className={styles.section}><button className={styles.sectionHeader} aria-expanded={open} aria-controls={id} onClick={onClick}><span><Icon size={18} />{title}</span><ChevronDown className={open ? styles.rotate : ''} size={17} /></button>{open && <div id={id} className={styles.sectionBody}>{children}</div>}</section> }
